import type { Room, Supplier } from "@/lib/admin/types"

export const seedSuppliers: Supplier[] = [
  {
    id: "supplier-1",
    supplierCode: "NCC-000001",
    fullName: "Nguyễn Minh An",
    citizenId: "000000000101",
    age: 34,
    gender: "male",
    address: "Phường Bãi Cháy, thành phố Hạ Long, Quảng Ninh",
    phone: "0900000101",
    zalo: "0900000101",
    facebookUrl: "https://facebook.com/demo.ncc001",
    tiktokUrl: "",
    email: "ncc001@example.com",
    serviceAreas: [
      {
        id: "area-1",
        country: "Việt Nam",
        provinceCity: "Quảng Ninh",
        districtCity: "Thành phố Hạ Long",
      },
    ],
    serviceTypes: ["accommodation", "transfer"],
    accommodationTypes: ["homestay", "apartment", "villa"],
    status: "active",
    internalNote: "Ưu tiên các phòng view biển, phản hồi nhanh qua Zalo.",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-28",
  },
  {
    id: "supplier-2",
    supplierCode: "NCC-000002",
    fullName: "Lê Hoàng Phúc",
    citizenId: "000000000202",
    age: 41,
    gender: "male",
    address: "Phường Cẩm An, thành phố Hội An, Quảng Nam",
    phone: "0900000202",
    zalo: "0900000202",
    facebookUrl: "",
    tiktokUrl: "",
    email: "ncc002@example.com",
    serviceAreas: [
      {
        id: "area-2",
        country: "Việt Nam",
        provinceCity: "Quảng Nam",
        districtCity: "Hội An",
      },
    ],
    serviceTypes: ["accommodation", "tour", "vehicle_rental"],
    accommodationTypes: ["villa", "whole_house", "homestay"],
    status: "active",
    internalNote: "Có thêm dịch vụ thuê xe máy tại Hội An.",
    createdAt: "2026-06-02",
    updatedAt: "2026-06-27",
  },
  {
    id: "supplier-3",
    supplierCode: "NCC-000003",
    fullName: "Trần Bảo Ngọc",
    citizenId: "000000000303",
    age: 29,
    gender: "female",
    address: "Phường 1, thành phố Đà Lạt, Lâm Đồng",
    phone: "0900000303",
    zalo: "0900000303",
    facebookUrl: "https://facebook.com/demo.ncc003",
    tiktokUrl: "https://www.tiktok.com/@demo_ncc003",
    email: "ncc003@example.com",
    serviceAreas: [
      {
        id: "area-3",
        country: "Việt Nam",
        provinceCity: "Lâm Đồng",
        districtCity: "Đà Lạt",
      },
    ],
    serviceTypes: ["accommodation", "guide"],
    accommodationTypes: ["studio", "homestay", "guesthouse"],
    status: "active",
    internalNote: "Phù hợp nhóm khách trẻ, có nhiều studio nhỏ.",
    createdAt: "2026-06-04",
    updatedAt: "2026-06-25",
  },
  {
    id: "supplier-4",
    supplierCode: "NCC-000004",
    fullName: "Phạm Quốc Bảo",
    citizenId: "000000000404",
    age: 38,
    gender: "male",
    address: "Thảo Điền, thành phố Thủ Đức, TP. Hồ Chí Minh",
    phone: "0900000404",
    zalo: "0900000404",
    facebookUrl: "",
    tiktokUrl: "",
    email: "ncc004@example.com",
    serviceAreas: [
      {
        id: "area-4",
        country: "Việt Nam",
        provinceCity: "TP. Hồ Chí Minh",
        districtCity: "Thành phố Thủ Đức",
      },
    ],
    serviceTypes: ["accommodation"],
    accommodationTypes: ["apartment", "whole_house"],
    status: "paused",
    internalNote: "Tạm ngưng nhận booking cuối tuần, cần xác nhận trước.",
    createdAt: "2026-06-05",
    updatedAt: "2026-06-20",
  },
  {
    id: "supplier-5",
    supplierCode: "NCC-000005",
    fullName: "Đỗ Thảo Vy",
    citizenId: "000000000505",
    age: 33,
    gender: "female",
    address: "An Thới, Phú Quốc, Kiên Giang",
    phone: "0900000505",
    zalo: "0900000505",
    facebookUrl: "",
    tiktokUrl: "",
    email: "ncc005@example.com",
    serviceAreas: [
      {
        id: "area-5",
        country: "Việt Nam",
        provinceCity: "Kiên Giang",
        districtCity: "Phú Quốc",
      },
    ],
    serviceTypes: ["accommodation", "tour", "transfer"],
    accommodationTypes: ["villa", "homestay", "guesthouse"],
    status: "active",
    internalNote: "Có tour đảo và xe đưa đón sân bay theo yêu cầu.",
    createdAt: "2026-06-07",
    updatedAt: "2026-06-24",
  },
  {
    id: "supplier-6",
    supplierCode: "NCC-000006",
    fullName: "Vũ Khánh Linh",
    citizenId: "000000000606",
    age: 31,
    gender: "female",
    address: "Quận Hoàn Kiếm, Hà Nội",
    phone: "0900000606",
    zalo: "0900000606",
    facebookUrl: "https://facebook.com/demo.ncc006",
    tiktokUrl: "",
    email: "ncc006@example.com",
    serviceAreas: [
      {
        id: "area-6",
        country: "Việt Nam",
        provinceCity: "Hà Nội",
        districtCity: "Hoàn Kiếm",
      },
    ],
    serviceTypes: ["accommodation", "flight_ticket"],
    accommodationTypes: ["homestay", "apartment", "hotel"],
    status: "active",
    internalNote: "Có thể hỗ trợ vé máy bay theo đoàn nhỏ.",
    createdAt: "2026-06-08",
    updatedAt: "2026-06-23",
  },
  {
    id: "supplier-7",
    supplierCode: "NCC-000007",
    fullName: "Hồ Gia Hân",
    citizenId: "000000000707",
    age: 27,
    gender: "female",
    address: "Sơn Trà, Đà Nẵng",
    phone: "0900000707",
    zalo: "0900000707",
    facebookUrl: "",
    tiktokUrl: "https://www.tiktok.com/@demo_ncc007",
    email: "ncc007@example.com",
    serviceAreas: [
      {
        id: "area-7",
        country: "Việt Nam",
        provinceCity: "Đà Nẵng",
        districtCity: "Sơn Trà",
      },
    ],
    serviceTypes: ["accommodation", "guide", "transfer"],
    accommodationTypes: ["hotel", "apartment", "studio"],
    status: "active",
    internalNote: "Ưu tiên khách cần lưu trú gần biển Mỹ Khê.",
    createdAt: "2026-06-10",
    updatedAt: "2026-06-26",
  },
  {
    id: "supplier-8",
    supplierCode: "NCC-000008",
    fullName: "Mai Nhật Minh",
    citizenId: "000000000808",
    age: 45,
    gender: "prefer_not_to_say",
    address: "Nha Trang, Khánh Hòa",
    phone: "0900000808",
    zalo: "0900000808",
    facebookUrl: "",
    tiktokUrl: "",
    email: "ncc008@example.com",
    serviceAreas: [
      {
        id: "area-8",
        country: "Việt Nam",
        provinceCity: "Khánh Hòa",
        districtCity: "Nha Trang",
      },
    ],
    serviceTypes: ["accommodation", "tour"],
    accommodationTypes: ["hotel", "villa", "apartment"],
    status: "discontinued",
    internalNote: "Đã ngừng khai thác thử nghiệm, giữ dữ liệu để đối chiếu.",
    createdAt: "2026-06-12",
    updatedAt: "2026-06-18",
  },
]

const sharedPolicies = {
  checkInTime: "14:00",
  checkOutTime: "12:00",
  smoking: "not_allowed" as const,
  pets: "conditional" as const,
  cancellationType: "conditional" as const,
  cancellationDetail: "Hủy trước 3 ngày được hoàn cọc 90%.",
  depositRequired: true,
  depositDetail: "Đặt cọc 30% để giữ phòng.",
  minimumNights: 1,
  quietHours: "",
  otherPolicy: "",
}

export const seedRooms: Room[] = [
  {
    id: "room-1",
    roomCode: "PH-000001",
    name: "Homestay view biển Hạ Long",
    status: "published",
    accommodationTypes: ["homestay"],
    otherAccommodationType: "",
    description: "Phòng gần biển, phù hợp cho nhóm bạn hoặc gia đình nhỏ.",
    areaM2: 35,
    capacity: {
      maxGuests: 4,
      bedrooms: 1,
      bathrooms: 1,
      beds: 2,
    },
    supplierId: "supplier-1",
    pricing: {
      supplierPrice: 650000,
      commissionType: "percentage",
      commissionValue: 10,
      referencePrice: 850000,
      strikethroughPrice: 990000,
      priceUnit: "per_night",
      priceNote: "",
    },
    location: {
      provinceCity: "Quảng Ninh",
      districtCity: "Thành phố Hạ Long",
      addressDetail: "154 đường Bãi Muối, thành phố Hạ Long, Quảng Ninh",
      googleMapsUrl: "https://maps.google.com/?q=Ha+Long",
      nearbyTags: ["near_beach", "near_center"],
      distanceToCenter: "under_3km",
    },
    policies: sharedPolicies,
    amenities: ["free_wifi", "air_conditioning", "free_parking"],
    customAmenities: [],
    media: {
      images: [
        {
          id: "image-1",
          url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1400&q=80",
          caption: "Không gian nghỉ dưỡng gần biển",
          isThumbnail: true,
        },
        {
          id: "image-2",
          url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1400&q=80",
          caption: "Phòng ngủ sáng sủa",
          isThumbnail: false,
        },
      ],
      videoUrls: ["https://www.youtube.com/watch?v=ysz5S6PUM-U"],
    },
    seo: {
      slug: "homestay-view-bien-ha-long",
      metaTitle: "",
      metaDescription: "",
      shareThumbnailImageId: "image-1",
    },
    isFeatured: true,
    displayPriority: 1,
    createdAt: "2026-06-15",
    updatedAt: "2026-06-29",
    createdBy: "Admin Demo",
    updatedBy: "Admin Demo",
  },
  {
    id: "room-2",
    roomCode: "PH-000002",
    name: "Villa hồ bơi An Bàng",
    status: "published",
    accommodationTypes: ["villa", "whole_house"],
    otherAccommodationType: "",
    description: "Villa riêng tư gần biển An Bàng, có hồ bơi và bếp đầy đủ.",
    areaM2: 180,
    capacity: {
      maxGuests: 8,
      bedrooms: 3,
      bathrooms: 3,
      beds: 4,
    },
    supplierId: "supplier-2",
    pricing: {
      supplierPrice: 3100000,
      commissionType: "percentage",
      commissionValue: 10,
      referencePrice: 3950000,
      strikethroughPrice: 4600000,
      priceUnit: "per_night",
      priceNote: "Giá có thể thay đổi vào cuối tuần.",
    },
    location: {
      provinceCity: "Quảng Nam",
      districtCity: "Hội An",
      addressDetail: "Khu An Bàng, phường Cẩm An, thành phố Hội An",
      googleMapsUrl: "https://maps.google.com/?q=An+Bang+Hoi+An",
      nearbyTags: ["near_beach", "near_attraction"],
      distanceToCenter: "from_3_to_5km",
    },
    policies: {
      ...sharedPolicies,
      pets: "not_allowed",
      depositRequired: false,
      depositDetail: "",
    },
    amenities: ["free_wifi", "pool", "kitchen", "cleaning", "free_parking"],
    customAmenities: ["BBQ sân vườn"],
    media: {
      images: [
        {
          id: "image-3",
          url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80",
          caption: "Villa hiện đại có hồ bơi",
          isThumbnail: true,
        },
      ],
      videoUrls: [],
    },
    seo: {
      slug: "villa-ho-boi-an-bang",
      metaTitle: "",
      metaDescription: "",
      shareThumbnailImageId: "image-3",
    },
    isFeatured: true,
    displayPriority: 2,
    createdAt: "2026-06-16",
    updatedAt: "2026-06-28",
    createdBy: "Admin Demo",
    updatedBy: "Admin Demo",
  },
  {
    id: "room-3",
    roomCode: "PH-000003",
    name: "Studio trung tâm Đà Lạt",
    status: "draft",
    accommodationTypes: ["studio"],
    otherAccommodationType: "",
    description: "Studio gọn trong khu trung tâm, thuận tiện đi bộ.",
    areaM2: 32,
    capacity: {
      maxGuests: 2,
      bedrooms: 1,
      bathrooms: 1,
      beds: 1,
    },
    supplierId: "supplier-3",
    pricing: {
      supplierPrice: 720000,
      commissionType: "percentage",
      commissionValue: 15,
      referencePrice: 980000,
      strikethroughPrice: 1250000,
      priceUnit: "per_night",
      priceNote: "",
    },
    location: {
      provinceCity: "Lâm Đồng",
      districtCity: "Đà Lạt",
      addressDetail: "Đường Nguyễn Chí Thanh, phường 1, thành phố Đà Lạt",
      googleMapsUrl: "https://maps.google.com/?q=Da+Lat",
      nearbyTags: ["near_center", "near_market"],
      distanceToCenter: "under_3km",
    },
    policies: sharedPolicies,
    amenities: ["free_wifi", "hot_water", "desk", "kitchen"],
    customAmenities: [],
    media: {
      images: [],
      videoUrls: [],
    },
    seo: {
      slug: "studio-trung-tam-da-lat",
      metaTitle: "",
      metaDescription: "",
    },
    isFeatured: false,
    displayPriority: 5,
    createdAt: "2026-06-17",
    updatedAt: "2026-06-22",
    createdBy: "Admin Demo",
    updatedBy: "Admin Demo",
  },
  {
    id: "room-4",
    roomCode: "PH-000004",
    name: "Penthouse sông Sài Gòn",
    status: "hidden",
    accommodationTypes: ["apartment"],
    otherAccommodationType: "",
    description: "Penthouse tầng cao có tầm nhìn về sông, phòng khách rộng.",
    areaM2: 120,
    capacity: {
      maxGuests: 4,
      bedrooms: 2,
      bathrooms: 2,
      beds: 2,
    },
    supplierId: "supplier-4",
    pricing: {
      supplierPrice: 4200000,
      commissionType: "fixed",
      commissionValue: 350000,
      referencePrice: 5200000,
      strikethroughPrice: 6200000,
      priceUnit: "per_night",
      priceNote: "",
    },
    location: {
      provinceCity: "TP. Hồ Chí Minh",
      districtCity: "Thành phố Thủ Đức",
      addressDetail: "Khu Thảo Điền, thành phố Thủ Đức",
      googleMapsUrl: "https://maps.google.com/?q=Thao+Dien",
      nearbyTags: ["near_center"],
      distanceToCenter: "over_5km",
    },
    policies: sharedPolicies,
    amenities: ["free_wifi", "pool", "city_view", "free_parking"],
    customAmenities: [],
    media: {
      images: [
        {
          id: "image-4",
          url: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=80",
          caption: "Căn hộ tầng cao",
          isThumbnail: true,
        },
      ],
      videoUrls: ["https://vimeo.com/76979871"],
    },
    seo: {
      slug: "penthouse-song-sai-gon",
      metaTitle: "",
      metaDescription: "",
      shareThumbnailImageId: "image-4",
    },
    isFeatured: true,
    displayPriority: 3,
    createdAt: "2026-06-18",
    updatedAt: "2026-06-25",
    createdBy: "Admin Demo",
    updatedBy: "Admin Demo",
  },
  {
    id: "room-5",
    roomCode: "PH-000005",
    name: "Bungalow Bãi Sao Phú Quốc",
    status: "pending_completion",
    accommodationTypes: ["guesthouse", "homestay"],
    otherAccommodationType: "",
    description: "Bungalow trong khu vườn yên tĩnh, cách biển một quãng ngắn.",
    areaM2: 52,
    capacity: {
      maxGuests: 3,
      bedrooms: 1,
      bathrooms: 1,
      beds: 2,
    },
    pricing: {
      supplierPrice: 1650000,
      commissionType: "percentage",
      commissionValue: 11,
      referencePrice: 2150000,
      strikethroughPrice: 2600000,
      priceUnit: "per_night",
      priceNote: "",
    },
    location: {
      provinceCity: "Kiên Giang",
      districtCity: "Phú Quốc",
      addressDetail: "Khu Bãi Sao, phường An Thới, Phú Quốc",
      googleMapsUrl: "https://maps.google.com/?q=Bai+Sao+Phu+Quoc",
      nearbyTags: ["near_beach"],
      distanceToCenter: "over_5km",
    },
    policies: sharedPolicies,
    amenities: ["free_wifi", "breakfast", "airport_pickup"],
    customAmenities: [],
    media: {
      images: [
        {
          id: "image-5",
          url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1400&q=80",
          caption: "Phòng nghỉ trong khu vườn",
          isThumbnail: true,
        },
      ],
      videoUrls: [],
    },
    seo: {
      slug: "bungalow-bai-sao-phu-quoc",
      metaTitle: "",
      metaDescription: "",
      shareThumbnailImageId: "image-5",
    },
    isFeatured: false,
    displayPriority: 6,
    createdAt: "2026-06-18",
    updatedAt: "2026-06-21",
    createdBy: "Admin Demo",
    updatedBy: "Admin Demo",
  },
  {
    id: "room-6",
    roomCode: "PH-000006",
    name: "Homestay phố cổ Hà Nội",
    status: "published",
    accommodationTypes: ["homestay", "apartment"],
    otherAccommodationType: "",
    description:
      "Homestay trong khu phố cổ, thuận tiện đi bộ đến hồ Hoàn Kiếm.",
    areaM2: 38,
    capacity: {
      maxGuests: 2,
      bedrooms: 1,
      bathrooms: 1,
      beds: 1,
    },
    supplierId: "supplier-6",
    pricing: {
      supplierPrice: 890000,
      commissionType: "percentage",
      commissionValue: 14,
      referencePrice: 1180000,
      strikethroughPrice: 1500000,
      priceUnit: "per_night",
      priceNote: "",
    },
    location: {
      provinceCity: "Hà Nội",
      districtCity: "Hoàn Kiếm",
      addressDetail: "Phố Hàng Bạc, quận Hoàn Kiếm",
      googleMapsUrl: "https://maps.google.com/?q=Hoan+Kiem",
      nearbyTags: ["near_center", "near_market"],
      distanceToCenter: "under_3km",
    },
    policies: sharedPolicies,
    amenities: ["free_wifi", "air_conditioning", "kitchen", "hot_water"],
    customAmenities: ["Tự check-in"],
    media: {
      images: [
        {
          id: "image-6",
          url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1400&q=80",
          caption: "Homestay phố cổ",
          isThumbnail: true,
        },
      ],
      videoUrls: ["https://www.youtube.com/watch?v=jNQXAC9IVRw"],
    },
    seo: {
      slug: "homestay-pho-co-ha-noi",
      metaTitle: "",
      metaDescription: "",
      shareThumbnailImageId: "image-6",
    },
    isFeatured: false,
    displayPriority: 4,
    createdAt: "2026-06-19",
    updatedAt: "2026-06-26",
    createdBy: "Admin Demo",
    updatedBy: "Admin Demo",
  },
  {
    id: "room-7",
    roomCode: "PH-000007",
    name: "Khách sạn gần biển Mỹ Khê",
    status: "published",
    accommodationTypes: ["hotel"],
    otherAccommodationType: "",
    description: "Phòng khách sạn gọn, gần biển Mỹ Khê và khu ăn uống.",
    areaM2: 28,
    capacity: {
      maxGuests: 2,
      bedrooms: 1,
      bathrooms: 1,
      beds: 1,
    },
    supplierId: "supplier-7",
    pricing: {
      supplierPrice: 980000,
      commissionType: "fixed",
      commissionValue: 120000,
      referencePrice: 1350000,
      strikethroughPrice: 0,
      priceUnit: "per_night",
      priceNote: "",
    },
    location: {
      provinceCity: "Đà Nẵng",
      districtCity: "Sơn Trà",
      addressDetail: "Võ Nguyên Giáp, phường Phước Mỹ, Sơn Trà",
      googleMapsUrl: "https://maps.google.com/?q=My+Khe+Beach",
      nearbyTags: ["near_beach", "near_center"],
      distanceToCenter: "from_3_to_5km",
    },
    policies: sharedPolicies,
    amenities: ["free_wifi", "air_conditioning", "front_desk", "cleaning"],
    customAmenities: [],
    media: {
      images: [
        {
          id: "image-7",
          url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=80",
          caption: "Khách sạn gần biển",
          isThumbnail: true,
        },
      ],
      videoUrls: [],
    },
    seo: {
      slug: "khach-san-gan-bien-my-khe",
      metaTitle: "",
      metaDescription: "",
      shareThumbnailImageId: "image-7",
    },
    isFeatured: true,
    displayPriority: 7,
    createdAt: "2026-06-20",
    updatedAt: "2026-06-27",
    createdBy: "Admin Demo",
    updatedBy: "Admin Demo",
  },
  {
    id: "room-8",
    roomCode: "PH-000008",
    name: "Căn hộ gia đình Tây Hồ",
    status: "pending_completion",
    accommodationTypes: ["apartment"],
    otherAccommodationType: "",
    description: "Căn hộ hai phòng ngủ phù hợp gia đình nhỏ ở Tây Hồ.",
    areaM2: 75,
    capacity: {
      maxGuests: 5,
      bedrooms: 2,
      bathrooms: 2,
      beds: 3,
    },
    supplierId: "supplier-6",
    pricing: {
      supplierPrice: 1600000,
      commissionType: "percentage",
      commissionValue: 12,
      referencePrice: 2100000,
      strikethroughPrice: 2450000,
      priceUnit: "per_night",
      priceNote: "",
    },
    location: {
      provinceCity: "Hà Nội",
      districtCity: "Tây Hồ",
      addressDetail: "Đường Xuân Diệu, quận Tây Hồ",
      googleMapsUrl: "",
      nearbyTags: ["near_center"],
      distanceToCenter: "from_3_to_5km",
    },
    policies: {
      ...sharedPolicies,
      checkInTime: "",
      checkOutTime: "",
    },
    amenities: ["free_wifi", "kitchen", "washing_machine", "family_friendly"],
    customAmenities: [],
    media: {
      images: [],
      videoUrls: [],
    },
    seo: {
      slug: "can-ho-gia-dinh-tay-ho",
      metaTitle: "",
      metaDescription: "",
    },
    isFeatured: false,
    displayPriority: 8,
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
    createdBy: "Admin Demo",
    updatedBy: "Admin Demo",
  },
  {
    id: "room-9",
    roomCode: "PH-000009",
    name: "Du thuyền vịnh Hạ Long",
    status: "discontinued",
    accommodationTypes: ["cruise"],
    otherAccommodationType: "",
    description: "Cabin du thuyền thử nghiệm, đã ngừng hợp tác.",
    areaM2: 24,
    capacity: {
      maxGuests: 2,
      bedrooms: 1,
      bathrooms: 1,
      beds: 1,
    },
    supplierId: "supplier-1",
    pricing: {
      supplierPrice: 2800000,
      commissionType: "percentage",
      commissionValue: 8,
      referencePrice: 3350000,
      strikethroughPrice: 0,
      priceUnit: "per_night",
      priceNote: "Không còn khai thác trong prototype.",
    },
    location: {
      provinceCity: "Quảng Ninh",
      districtCity: "Thành phố Hạ Long",
      addressDetail: "Cảng tàu du lịch quốc tế Hạ Long",
      googleMapsUrl: "",
      nearbyTags: ["near_beach", "near_attraction"],
      distanceToCenter: "from_3_to_5km",
    },
    policies: sharedPolicies,
    amenities: ["free_wifi", "breakfast", "sea_view"],
    customAmenities: [],
    media: {
      images: [
        {
          id: "image-8",
          url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80",
          caption: "Cabin du thuyền",
          isThumbnail: true,
        },
      ],
      videoUrls: [],
    },
    seo: {
      slug: "du-thuyen-vinh-ha-long",
      metaTitle: "",
      metaDescription: "",
      shareThumbnailImageId: "image-8",
    },
    isFeatured: false,
    displayPriority: 9,
    createdAt: "2026-06-12",
    updatedAt: "2026-06-19",
    createdBy: "Admin Demo",
    updatedBy: "Admin Demo",
  },
  {
    id: "room-10",
    roomCode: "PH-000010",
    name: "Nhà nguyên căn Nha Trang",
    status: "draft",
    accommodationTypes: ["whole_house", "other"],
    otherAccommodationType: "Nhà phố nhiều tầng",
    description: "Nhà nguyên căn cần bổ sung ảnh trước khi đăng.",
    areaM2: 95,
    capacity: {
      maxGuests: 6,
      bedrooms: 3,
      bathrooms: 2,
      beds: 3,
    },
    supplierId: "supplier-8",
    pricing: {
      supplierPrice: 2200000,
      commissionType: "fixed",
      commissionValue: 250000,
      referencePrice: 2850000,
      strikethroughPrice: 0,
      priceUnit: "per_night",
      priceNote: "",
    },
    location: {
      provinceCity: "Khánh Hòa",
      districtCity: "Nha Trang",
      addressDetail: "Khu vực Hòn Chồng, thành phố Nha Trang",
      googleMapsUrl: "",
      nearbyTags: ["near_beach", "near_market"],
      distanceToCenter: "from_3_to_5km",
    },
    policies: sharedPolicies,
    amenities: ["free_wifi", "kitchen", "washing_machine", "group_friendly"],
    customAmenities: [],
    media: {
      images: [],
      videoUrls: [],
    },
    seo: {
      slug: "nha-nguyen-can-nha-trang",
      metaTitle: "",
      metaDescription: "",
    },
    isFeatured: false,
    displayPriority: 10,
    createdAt: "2026-06-14",
    updatedAt: "2026-06-18",
    createdBy: "Admin Demo",
    updatedBy: "Admin Demo",
  },
]
