import type { PublicRentalListing } from "@/lib/rentals/types"

const baseDate = "2026-07-22"

export const demoRentalListings: PublicRentalListing[] = [
  {
    id: "rental-demo-1",
    code: "PT000001",
    source: "admin",
    supplierId: "supplier-demo-1",
    name: "Phòng trọ có gác gần Đại học Văn Lang",
    publicationStatus: "published",
    availabilityStatus: "available",
    rentalType: "boarding_room",
    otherRentalType: "",
    description:
      "Phòng sáng thoáng, có gác lửng và WC riêng, phù hợp sinh viên hoặc người đi làm.",
    monthlyPrice: 3500000,
    areaM2: 24,
    maxOccupants: 2,
    city: "TP. Hồ Chí Minh",
    newProvince: "Thành phố Hồ Chí Minh",
    newWard: "Phường Gia Định",
    legacyWard: "Phường 25",
    legacyDistrict: "Quận Bình Thạnh",
    addressDetail: "Đường D2, Phường Gia Định, TP. Hồ Chí Minh",
    googleMapsUrl: "https://maps.google.com/",
    nearbyPlaces: ["Đại học Văn Lang", "Bến xe Miền Đông", "Landmark 81"],
    electricityPrice: "4.000đ/kWh",
    waterPrice: "100.000đ/người/tháng",
    otherCosts: "Gửi xe và internet trao đổi khi xem phòng.",
    amenities: ["air_conditioner", "bed", "private_toilet", "mezzanine"],
    customAmenities: [],
    allowedRules: ["Nấu ăn", "Giờ giấc tự do"],
    disallowedRules: ["Hút thuốc trong phòng"],
    media: {
      images: [
        {
          id: "rental-demo-image-1",
          url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=85",
          caption: "Không gian phòng",
          isThumbnail: true,
        },
        {
          id: "rental-demo-image-2",
          url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=85",
          caption: "Khu vực giường",
          isThumbnail: false,
        },
        {
          id: "rental-demo-image-3",
          url: "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=1400&q=85",
          caption: "Góc sinh hoạt",
          isThumbnail: false,
        },
      ],
      videoUrls: [],
    },
    internalNote: "",
    hiddenReason: "",
    ownerVerified: true,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    id: "rental-demo-2",
    code: "PT000002",
    source: "admin",
    supplierId: "supplier-demo-2",
    name: "Căn hộ mini có ban công tại Quận 10",
    publicationStatus: "published",
    availabilityStatus: "available",
    rentalType: "mini_apartment",
    otherRentalType: "",
    description:
      "Căn hộ mini riêng tư, nội thất cơ bản, khu dân cư yên tĩnh và thuận tiện đi trung tâm.",
    monthlyPrice: 5800000,
    areaM2: 30,
    maxOccupants: 2,
    city: "TP. Hồ Chí Minh",
    newProvince: "Thành phố Hồ Chí Minh",
    newWard: "Phường Hòa Hưng",
    legacyWard: "Phường 13",
    legacyDistrict: "Quận 10",
    addressDetail: "Đường Tô Hiến Thành, Phường Hòa Hưng, TP. Hồ Chí Minh",
    googleMapsUrl: "https://maps.google.com/",
    nearbyPlaces: ["Đại học Bách Khoa", "Vạn Hạnh Mall"],
    electricityPrice: "4.000đ/kWh",
    waterPrice: "Theo đồng hồ",
    otherCosts: "Các chi phí khác trao đổi trực tiếp với Roovea.",
    amenities: [
      "air_conditioner",
      "water_heater",
      "bed",
      "wardrobe",
      "balcony",
      "private_toilet",
    ],
    customAmenities: [],
    allowedRules: ["Nấu ăn"],
    disallowedRules: ["Nuôi thú cưng"],
    media: {
      images: [
        {
          id: "rental-demo-image-4",
          url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1400&q=85",
          caption: "Căn hộ mini",
          isThumbnail: true,
        },
        {
          id: "rental-demo-image-5",
          url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1400&q=85",
          caption: "Không gian sinh hoạt",
          isThumbnail: false,
        },
        {
          id: "rental-demo-image-6",
          url: "https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=1400&q=85",
          caption: "Khu bếp",
          isThumbnail: false,
        },
      ],
      videoUrls: [],
    },
    internalNote: "",
    hiddenReason: "",
    ownerVerified: false,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
  {
    id: "rental-demo-3",
    code: "PT000003",
    source: "admin",
    supplierId: "supplier-demo-3",
    name: "Phòng có cửa sổ lớn gần Đại học Tôn Đức Thắng",
    publicationStatus: "published",
    availabilityStatus: "available",
    rentalType: "room_in_house",
    otherRentalType: "",
    description:
      "Phòng trong nhà nguyên căn, có cửa sổ lớn, bàn học và khu bếp sử dụng thuận tiện.",
    monthlyPrice: 4200000,
    areaM2: 22,
    maxOccupants: 2,
    city: "TP. Hồ Chí Minh",
    newProvince: "Thành phố Hồ Chí Minh",
    newWard: "Phường Tân Hưng",
    legacyWard: "Phường Tân Phong",
    legacyDistrict: "Quận 7",
    addressDetail: "Đường Lê Văn Lương, Phường Tân Hưng, TP. Hồ Chí Minh",
    googleMapsUrl: "https://maps.google.com/",
    nearbyPlaces: ["Đại học Tôn Đức Thắng", "Lotte Mart Quận 7"],
    electricityPrice: "3.800đ/kWh",
    waterPrice: "90.000đ/người/tháng",
    otherCosts: "",
    amenities: ["desk", "window", "kitchen", "washing_machine"],
    customAmenities: [],
    allowedRules: ["Tiếp khách trước 22:00"],
    disallowedRules: ["Hút thuốc"],
    media: {
      images: [
        {
          id: "rental-demo-image-7",
          url: "https://images.unsplash.com/photo-1560185009-dddeb820c7b7?auto=format&fit=crop&w=1400&q=85",
          caption: "Phòng có cửa sổ",
          isThumbnail: true,
        },
        {
          id: "rental-demo-image-8",
          url: "https://images.unsplash.com/photo-1615874694520-474822394e73?auto=format&fit=crop&w=1400&q=85",
          caption: "Bàn học",
          isThumbnail: false,
        },
        {
          id: "rental-demo-image-9",
          url: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1400&q=85",
          caption: "Giường ngủ",
          isThumbnail: false,
        },
      ],
      videoUrls: [],
    },
    internalNote: "",
    hiddenReason: "",
    ownerVerified: true,
    createdAt: baseDate,
    updatedAt: baseDate,
  },
]
